"""Generate the checked-in 7r/6s rank-constraint runtime template."""

from __future__ import annotations

import argparse
import hashlib
import json
from itertools import combinations
from pathlib import Path

DIMENSION = 3
RECEIVER_COUNT = 7
EVENT_COUNT = 6
GENERIC_COMPLEX_SOLUTION_COUNT = 5


def _payload() -> dict[str, object]:
    primary = [[[0, 1, 2, row], [0, 1, 2, column]] for row in (3, 4, 5) for column in (3, 4)]
    all_specs = [
        [list(rows), list(columns)]
        for rows in combinations(range(RECEIVER_COUNT - 1), DIMENSION + 1)
        for columns in combinations(range(EVENT_COUNT - 1), DIMENSION + 1)
    ]
    return {
        "version": 1,
        "dimension": DIMENSION,
        "receiver_count": RECEIVER_COUNT,
        "event_count": EVENT_COUNT,
        "generic_complex_solution_count": GENERIC_COMPLEX_SOLUTION_COUNT,
        "primary_minor_specs": primary,
        "all_minor_specs": all_specs,
    }


def render_generated_template() -> str:
    payload = _payload()
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return (
        '"""Generated 7r/6s rank-constraint template.\n\n'
        "Generated by tools/generate_7r6s_template.py.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"TEMPLATE_VERSION = {payload['version']}\n"
        f"DIMENSION = {payload['dimension']}\n"
        f"RECEIVER_COUNT = {payload['receiver_count']}\n"
        f"EVENT_COUNT = {payload['event_count']}\n"
        "GENERIC_COMPLEX_SOLUTION_COUNT = "
        f"{payload['generic_complex_solution_count']}\n"
        "# fmt: off\n"
        "PRIMARY_MINOR_SPECS = "
        f"{json.dumps(payload['primary_minor_specs'], separators=(',', ':'))}\n"
        "ALL_MINOR_SPECS = "
        f"{json.dumps(payload['all_minor_specs'], separators=(',', ':'))}\n"
        "# fmt: on\n"
        f'TEMPLATE_SHA256 = "{digest}"\n'
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/acoustic_self_calibration/stratified/generated_7r6s.py"),
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_generated_template(), encoding="utf-8")


if __name__ == "__main__":
    main()
